# BOOK RECOMMENDATION SYSTEM

In [1]:
#importing file and libraries 
import pandas as pd
import numpy as np

df = pd.read_excel("BOOKS.xlsx")

In [2]:
df.head()

,book_id,title,subtitle,authors,publisher,published_date,description,page_count,categories,average_rating,...,language,preview_link,info_link,isbn_13,isbn_10,list_price,currency,buyable,search_category,thumbnail
0,LR_VDQAAQBAJ,Bestsellers,"The Path (bestsellers, free bestsellers, bests...","Ivan King, bestsellers",bestsellers,2017-01-04 00:00:00,"Hear What the Critics are Saying ""Wow, what an...",70.0,Young Adult Fiction,NaN,...,en,http://books.google.com/books?id=LR_VDQAAQBAJ&...,https://play.google.com/store/books/details?id...,NaN,NaN,12.99,USD,True,fiction bestsellers,http://books.google.com/books/content?id=LR_VD...
1,WcjTDQAAQBAJ,Bestsellers,"Hell: A Place Without Hope (bestseller books, ...","Ivan King, bestsellers",bestsellers,2017-01-03 00:00:00,"Hear What the Critics are Saying Wow, very ins...",32.0,Comics & Graphic Novels,NaN,...,en,http://books.google.com/books?id=WcjTDQAAQBAJ&...,https://play.google.com/store/books/details?id...,NaN,NaN,9.99,USD,True,fiction bestsellers,http://books.google.com/books/content?id=WcjTD...
2,4fXUDAAAQBAJ,The Bestseller Code,Anatomy of the Blockbuster Novel,"Jodie Archer, Matthew L. Jockers",Macmillan,2016-09-20 00:00:00,"""What if there was an algorithm that could pre...",253.0,Business & Economics,NaN,...,en,http://books.google.com/books?id=4fXUDAAAQBAJ&...,http://books.google.com/books?id=4fXUDAAAQBAJ&...,9.781250e+12,1250088275,NaN,NaN,False,fiction bestsellers,http://books.google.com/books/content?id=4fXUD...
3,yIVuDwAAQBAJ,Bestseller,A Century of America's Favorite Books,Robert McParland,Bloomsbury Publishing PLC,2018-12-15 00:00:00,Whether curled up on a sofa with a good myster...,335.0,Literary Criticism,NaN,...,en,http://books.google.com/books?id=yIVuDwAAQBAJ&...,https://play.google.com/store/books/details?id...,9.781538e+12,1538110008,40.50,USD,True,fiction bestsellers,http://books.google.com/books/content?id=yIVuD...
4,2JHXwAEACAAJ,Bestsellers: Popular Fiction since 1900,NaN,C. Bloom,Palgrave Macmillan,2002-07-09 00:00:00,This guide and reference work of all of the be...,306.0,Literary Criticism,NaN,...,en,http://books.google.com/books?id=2JHXwAEACAAJ&...,http://books.google.com/books?id=2JHXwAEACAAJ&...,9.780334e+12,333687426,NaN,NaN,False,fiction bestsellers,http://books.google.com/books/content?id=2JHXw...

In [3]:
df.shape

(15147, 21)

In [4]:
df.columns

Index(['book_id', 'title', 'subtitle', 'authors', 'publisher',
       'published_date', 'description', 'page_count', 'categories',
       'average_rating', 'ratings_count', 'language', 'preview_link',
       'info_link', 'isbn_13', 'isbn_10', 'list_price', 'currency', 'buyable',
       'search_category', 'thumbnail'],
      dtype='str')

In [5]:
df.info

<bound method DataFrame.info of             book_id                                    title  \
0      LR_VDQAAQBAJ                              Bestsellers
1      WcjTDQAAQBAJ                              Bestsellers
2      4fXUDAAAQBAJ                      The Bestseller Code
3      yIVuDwAAQBAJ                               Bestseller
4      2JHXwAEACAAJ  Bestsellers: Popular Fiction since 1900
...             ...                                      ...
15142  xeEdAQAAMAAJ                            DIY Retailing
15143           NaN                     Masquerade Evil Dual
15144           NaN                   Indiana Slavic Studies
15145  _3vfMAwwezwC                      The Literary Digest
15146  yqWlwa0S5twC                          Furniture Index

                                                subtitle  \
0      The Path (bestsellers, free bestsellers, bests...
1      Hell: A Place Without Hope (bestseller books, ...
2                       Anatomy of the Blockbuster Novel
3                  A Century of America's Favorite Books
4                                                    NaN
...                                                  ...
15142                                                NaN
15143                                                NaN
15144                                                NaN
15145                                                NaN
15146                                                NaN

                                                 authors  \
0                                 Ivan King, bestsellers
1                                 Ivan King, bestsellers
2                       Jodie Archer, Matthew L. Jockers
3                                       Robert McParland
4                                               C. Bloom
...                                                  ...
15142                                                NaN
15143                                    Suzwalt Lapoint
15144                                                NaN
15145  Edward Jewitt Wheeler, Isaac Kaufman Funk, Wil...
15146                                                NaN

                       publisher       published_date  \
0                    bestsellers  2017-01-04 00:00:00
1                    bestsellers  2017-01-03 00:00:00
2                      Macmillan  2016-09-20 00:00:00
3      Bloomsbury Publishing PLC  2018-12-15 00:00:00
4             Palgrave Macmillan  2002-07-09 00:00:00
...                          ...                  ...
15142                        NaN                 1985
15143                  Ace Books              1980-12
15144                        NaN                 2000
15145                        NaN                 1918
15146                        NaN                 1924

                                             description  page_count  \
0      Hear What the Critics are Saying "Wow, what an...        70.0
1      Hear What the Critics are Saying Wow, very ins...        32.0
2      "What if there was an algorithm that could pre...       253.0
3      Whether curled up on a sofa with a good myster...       335.0
4      This guide and reference work of all of the be...       306.0
...                                                  ...         ...
15142                                                NaN      1056.0
15143                                                NaN       420.0
15144                                                NaN       444.0
15145                                                NaN      1068.0
15146                                                NaN      1012.0

                         categories  average_rating  ...  language  \
0               Young Adult Fiction             NaN  ...        en
1           Comics & Graphic Novels             NaN  ...        en
2              Business & Economics             NaN  ...        en
3                Literary Criticism             NaN  ...        en
4                Literary Criticism             NaN  ...        en
...                             ...             ...  ...       ...
15142            Building materials             NaN  ...        en
15143                           NaN             NaN  ...        en
15144              Slavic countries             NaN  ...        en
15145                    Literature             NaN  ...        en
15146  Furniture industry and trade             NaN  ...        en

                                            preview_link  \
0      http://books.google.com/books?id=LR_VDQAAQBAJ&...
1      http://books.google.com/books?id=WcjTDQAAQBAJ&...
2      http://books.google.com/books?id=4fXUDAAAQBAJ&...
3      http://books.google.com/books?id=yIVuDwAAQBAJ&...
4      http://books.google.com/books?id=2JHXwAEACAAJ&...
...                                                  ...
15142  http://books.google.com/books?id=xeEdAQAAMAAJ&...
15143  http://books.google.com/books?id=-gG1i0B9EQ0C&...
15144  http://books.google.com/books?id=-Rdwn1PytagC&...
15145  http://books.google.com/books?id=_3vfMAwwezwC&...
15146  http://books.google.com/books?id=yqWlwa0S5twC&...

                                               info_link       isbn_13  \
0      https://play.google.com/store/books/details?id...           NaN
1      https://play.google.com/store/books/details?id...           NaN
2      http://books.google.com/books?id=4fXUDAAAQBAJ&...  9.781250e+12
3      https://play.google.com/store/books/details?id...  9.781538e+12
4      http://books.google.com/books?id=2JHXwAEACAAJ&...  9.780334e+12
...                                                  ...           ...
15142  http://books.google.com/books?id=xeEdAQAAMAAJ&...           NaN
15143  http://books.google.com/books?id=-gG1i0B9EQ0C&...  9.780442e+12
15144  http://books.google.com/books?id=-Rdwn1PytagC&...           NaN
15145  https://play.google.com/store/books/details?id...           NaN
15146  https://play.google.com/store/books/details?id...           NaN

          isbn_10 list_price  currency buyable      search_category  \
0             NaN      12.99       USD    True  fiction bestsellers
1             NaN       9.99       USD    True  fiction bestsellers
2      1250088275        NaN       NaN   False  fiction bestsellers
3      1538110008      40.50       USD    True  fiction bestsellers
4       333687426        NaN       NaN   False  fiction bestsellers
...           ...        ...       ...     ...                  ...
15142         NaN        NaN       NaN   False     language_English
15143  044152091X        NaN       NaN   False     language_English
15144         NaN        NaN       NaN   False     language_English
15145         NaN        NaN       NaN   False     language_English
15146         NaN        NaN       NaN   False     language_English

                                               thumbnail
0      http://books.google.com/books/content?id=LR_VD...
1      http://books.google.com/books/content?id=WcjTD...
2      http://books.google.com/books/content?id=4fXUD...
3      http://books.google.com/books/content?id=yIVuD...
4      http://books.google.com/books/content?id=2JHXw...
...                                                  ...
15142  http://books.google.com/books/content?id=xeEdA...
15143  http://books.google.com/books/content?id=-gG1i...
15144  http://books.google.com/books/content?id=-Rdwn...
15145  http://books.google.com/books/content?id=_3vfM...
15146  http://books.google.com/books/content?id=yqWlw...

[15147 rows x 21 columns]>

In [6]:
df.isnull().sum()

book_id              188
title                  8
subtitle            9165
authors             3525
publisher           8057
published_date       214
description         6798
page_count           214
categories          2452
average_rating     14290
ratings_count          0
language               0
preview_link           0
info_link              0
isbn_13             7764
isbn_10             8026
list_price         12204
currency           12204
buyable                0
search_category        0
thumbnail            669
dtype: int64

In [7]:
#create a clean dataset 
df = df = df[['book_id','title','authors','publisher','published_date','categories','description',
         'average_rating','ratings_count','page_count','language']]

In [8]:
df = df.dropna(subset=['title','authors','publisher','categories','description'])

In [9]:
df['average_rating'] = df['average_rating'].fillna(df['average_rating'].mean())

In [10]:
df = df.drop_duplicates(subset='title')

In [11]:
df = df.reset_index(drop=True)

In [12]:
#In columns publisher 
#remove missing publishers 
df['publisher'] = df['publisher'].fillna('Unknown')
#remove extra spaces 
df['publisher'] = df['publisher'].str.strip()
#convert to consistent format
df['publisher'] = df['publisher'].str.title()

In [13]:
df['published_date'] = pd.to_datetime(df['published_date'], utc=True)
#extracting year
df['published_year'] = df['published_date'].dt.year
#extracting month
df['published_month'] = df['published_date'].dt.month
#removing invalid years
df = df[df['published_year'] > 1900]

In [14]:
df.info

<bound method DataFrame.info of            book_id                                              title  \
0     LR_VDQAAQBAJ                                        Bestsellers
1     4fXUDAAAQBAJ                                The Bestseller Code
2     yIVuDwAAQBAJ                                         Bestseller
3     2JHXwAEACAAJ            Bestsellers: Popular Fiction since 1900
4     m4yBEAAAQBAJ                                               Hype
...            ...                                                ...
5930  D7NKUJ4_7NIC                                          Marketing
5931  1bNBEAAAQBAJ  Warriors: Exile from ShadowClan (Full-Color Ad...
5932  TvBDEAAAQBAJ                              Mothers and Daughters
5933  PiwrJrcwBUUC                    Quattro Pro for DOS for Dummies
5934  GMK2dC_rkKUC    Teach Yourself Microsoft PowerPoint 97 Visually

                                        authors                  publisher  \
0                        Ivan King, bestsellers                Bestsellers
1              Jodie Archer, Matthew L. Jockers                  Macmillan
2                              Robert McParland  Bloomsbury Publishing Plc
3                                      C. Bloom         Palgrave Macmillan
4     Jon Helgason, Sara KÃ¤rrholm, Ann Steiner      Nordic Academic Press
...                                         ...                        ...
5930                             Gary Armstrong              Prentice Hall
5931                                Erin Hunter              Harpercollins
5932                                Erica James           Harpercollins Uk
5933                            John Walkenbach                For Dummies
5934                                 Ruth Maran                     Visual

                          published_date            categories  \
0              2017-01-04 00:00:00+00:00   Young Adult Fiction
1              2016-09-20 00:00:00+00:00  Business & Economics
2              2018-12-15 00:00:00+00:00    Literary Criticism
3              2002-07-09 00:00:00+00:00    Literary Criticism
4              2015-01-01 00:00:00+00:00    Literary Criticism
...                                  ...                   ...
5930           2003-03-01 00:00:00+00:00  Business & Economics
5931           2022-06-07 00:00:00+00:00      Juvenile Fiction
5932           2022-03-17 00:00:00+00:00               Fiction
5933 1970-01-01 00:00:00.000001993+00:00             Computers
5934 1970-01-01 00:00:00.000001998+00:00             Computers

                                            description  average_rating  \
0     Hear What the Critics are Saying "Wow, what an...        4.092456
1     "What if there was an algorithm that could pre...        4.092456
2     Whether curled up on a sofa with a good myster...        4.092456
3     This guide and reference work of all of the be...        4.092456
4     In the world of books and literature, â€œhypeâ...        4.092456
...                                                 ...             ...
5930  Appropriate for students taking an introductor...        4.092456
5931  The warrior cats leap off the page in this ori...        5.000000
5932  A sweeping family drama of old secrets and new...        4.092456
5933  The fast and easy reference for the multi-face...        4.092456
5934  Learn to use all of PowerPoint 97's basic feat...        4.092456

      ratings_count  page_count language  published_year  published_month
0                 0        70.0       en          2017.0              1.0
1                 0       253.0       en          2016.0              9.0
2                 0       335.0       en          2018.0             12.0
3                 0       306.0       en          2002.0              7.0
4                 0       254.0       en          2015.0              1.0
...             ...         ...      ...             ...              ...
5930              0       784.0       en          2003.0              3.0
5931              1       228.0       en          2022.0              6.0
5932              0       421.0       en          2022.0              3.0
5933              0       384.0       en          1970.0              1.0
5934              0       308.0       en          1970.0              1.0

[5870 rows x 13 columns]>

In [15]:
df.isnull().sum()

book_id            76
title               0
authors             0
publisher           0
published_date      0
categories          0
description         0
average_rating      0
ratings_count       0
page_count          8
language            0
published_year      0
published_month     0
dtype: int64

In [16]:
#Remove Rows with Missing book_id
df = df.dropna(subset=['book_id'])

In [17]:
#Fill Missing Page Count
df['page_count'] = df['page_count'].fillna(df['page_count'].median())

In [18]:
df.isnull().sum()

book_id            0
title              0
authors            0
publisher          0
published_date     0
categories         0
description        0
average_rating     0
ratings_count      0
page_count         0
language           0
published_year     0
published_month    0
dtype: int64

In [19]:
df.shape

(5794, 13)

In [20]:
df.head

<bound method NDFrame.head of            book_id                                              title  \
0     LR_VDQAAQBAJ                                        Bestsellers
1     4fXUDAAAQBAJ                                The Bestseller Code
2     yIVuDwAAQBAJ                                         Bestseller
3     2JHXwAEACAAJ            Bestsellers: Popular Fiction since 1900
4     m4yBEAAAQBAJ                                               Hype
...            ...                                                ...
5930  D7NKUJ4_7NIC                                          Marketing
5931  1bNBEAAAQBAJ  Warriors: Exile from ShadowClan (Full-Color Ad...
5932  TvBDEAAAQBAJ                              Mothers and Daughters
5933  PiwrJrcwBUUC                    Quattro Pro for DOS for Dummies
5934  GMK2dC_rkKUC    Teach Yourself Microsoft PowerPoint 97 Visually

                                        authors                  publisher  \
0                        Ivan King, bestsellers                Bestsellers
1              Jodie Archer, Matthew L. Jockers                  Macmillan
2                              Robert McParland  Bloomsbury Publishing Plc
3                                      C. Bloom         Palgrave Macmillan
4     Jon Helgason, Sara KÃ¤rrholm, Ann Steiner      Nordic Academic Press
...                                         ...                        ...
5930                             Gary Armstrong              Prentice Hall
5931                                Erin Hunter              Harpercollins
5932                                Erica James           Harpercollins Uk
5933                            John Walkenbach                For Dummies
5934                                 Ruth Maran                     Visual

                          published_date            categories  \
0              2017-01-04 00:00:00+00:00   Young Adult Fiction
1              2016-09-20 00:00:00+00:00  Business & Economics
2              2018-12-15 00:00:00+00:00    Literary Criticism
3              2002-07-09 00:00:00+00:00    Literary Criticism
4              2015-01-01 00:00:00+00:00    Literary Criticism
...                                  ...                   ...
5930           2003-03-01 00:00:00+00:00  Business & Economics
5931           2022-06-07 00:00:00+00:00      Juvenile Fiction
5932           2022-03-17 00:00:00+00:00               Fiction
5933 1970-01-01 00:00:00.000001993+00:00             Computers
5934 1970-01-01 00:00:00.000001998+00:00             Computers

                                            description  average_rating  \
0     Hear What the Critics are Saying "Wow, what an...        4.092456
1     "What if there was an algorithm that could pre...        4.092456
2     Whether curled up on a sofa with a good myster...        4.092456
3     This guide and reference work of all of the be...        4.092456
4     In the world of books and literature, â€œhypeâ...        4.092456
...                                                 ...             ...
5930  Appropriate for students taking an introductor...        4.092456
5931  The warrior cats leap off the page in this ori...        5.000000
5932  A sweeping family drama of old secrets and new...        4.092456
5933  The fast and easy reference for the multi-face...        4.092456
5934  Learn to use all of PowerPoint 97's basic feat...        4.092456

      ratings_count  page_count language  published_year  published_month
0                 0        70.0       en          2017.0              1.0
1                 0       253.0       en          2016.0              9.0
2                 0       335.0       en          2018.0             12.0
3                 0       306.0       en          2002.0              7.0
4                 0       254.0       en          2015.0              1.0
...             ...         ...      ...             ...              ...
5930              0       784.0       en          2003.0              3.0
5931              1       228.0       en          2022.0              6.0
5932              0       421.0       en          2022.0              3.0
5933              0       384.0       en          1970.0              1.0
5934              0       308.0       en          1970.0              1.0

[5794 rows x 13 columns]>

In [21]:
df.to_csv("clean_books_dataset.csv", index=False)

# FEATURE ENGINEERING

In [22]:
#When multiple important "text columns" are combined together into "one" columns then it is called FEATURE.
#Machine Learning compares text information to understand similarity between books.
#If columns are kept in different colummns, the algorithm will not be able to compare them easily.

In [23]:
df['features'] = df[['title', 'authors', 'categories', 'publisher', 'description']].astype(str).agg(' '.join, axis=1)

In [24]:
#convert to lower case
df['features'] = df['features'].str.lower()

In [25]:
df[['title','features']].head()

,title,features
0,Bestsellers,"bestsellers ivan king, bestsellers young adult..."
1,The Bestseller Code,"the bestseller code jodie archer, matthew l. j..."
2,Bestseller,bestseller robert mcparland literary criticism...
3,Bestsellers: Popular Fiction since 1900,bestsellers: popular fiction since 1900 c. blo...
4,Hype,"hype jon helgason, sara kã¤rrholm, ann steiner..."

In [26]:
#Convert Text into Numbers (TF-IDF)
#TF-IDF is a technique used to convert text into numbers so that machines can understand and analyze text data.


from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['features'])

In [27]:
tfidf_matrix.shape

(5794, 56522)

### Similar Book recommendation

In [28]:
#calculating book similarity
#Calculate how 2 books are similar
#METHOD: Cosine Similarity - compares two vectors

from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tfidf_matrix)

In [29]:
similarity_matrix.shape

(5794, 5794)

In [30]:
# Build the Recommendation Function
def recommend_similar(book_title):

    book_title = book_title.lower()

    matches = df[df['title'].str.contains(book_title, case=False, na=False)]

    if matches.empty:
        print("Book not found in dataset.")
        return

    index = matches.index[0]

    similarity_scores = list(enumerate(similarity_matrix[index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)[1:6]

    for i in similarity_scores:
        book = df.iloc[i[0]]
        print(book['title'], "-", book['authors'], "(Rating:", book['average_rating'], ")")

In [31]:
df['title'].head(10)

0                                          Bestsellers
1                                  The Bestseller Code
2                                           Bestseller
3              Bestsellers: Popular Fiction since 1900
4                                                 Hype
5                                   Mary Higgins Clark
6                        A Richard Wright Bibliography
7    Publish. Profit. Independence. - How to Earn E...
8                                   Motivational Books
9     8 Great Habits of Extremely Effective Christians
Name: title, dtype: object

In [32]:
recommend_similar("bestsellers")

Suspense Books - Ivan King, suspense books (Rating: 4.0924556213017755 )
Young Adults - Ivan King, young adults (Rating: 4.0924556213017755 )
8 Great Habits of Extremely Effective Christians - Ivan King (Rating: 4.0924556213017755 )
Books About Life - Ivan King, books about life (Rating: 4.0924556213017755 )
Fantasy Books - I.G. Harding, fantasy books (Rating: 2.0 )

In [33]:
recommend_similar("Young Adults")

Books About Life - Ivan King, books about life (Rating: 4.0924556213017755 )
Inspirational Books - Ivan King, inspirational books (Rating: 4.0924556213017755 )
Inspirational Christian - Ivan King, inspirational christian (Rating: 4.0924556213017755 )
Christian Books - Ivan King, Christian (Rating: 4.0924556213017755 )
Personal Development - Ivan King, personal development (Rating: 4.0924556213017755 )

### Popular Book recommendation

In [34]:
#Popularity-Based Recommendation System
#Popularity Score Column
df['popularity_score'] = df['average_rating'] * np.log(df['ratings_count'] + 1)

In [35]:
#Sort Books by Popularity
popular_books = df.sort_values(by='popularity_score', ascending=False)

In [36]:
#View Top Popular Books
popular_books[['title','authors','average_rating','ratings_count','popularity_score']].head(10)

,title,authors,average_rating,ratings_count,popularity_score
5687,A Game of Thrones,George R. R. Martin,4.0,488,24.769450
5102,Harry Potter and the Deathly Hallows,J.K. Rowling,4.5,177,23.318026
5689,A Clash of Kings,George R. R. Martin,4.0,246,22.037553
4777,American Sniper,"Chris Kyle, Scott McEwen, Jim DeFelice",4.0,154,20.173700
5110,The Casual Vacancy,J. K. Rowling,3.0,826,20.153414
5107,Harry Potter and the Half-Blood Prince,J.K. Rowling,4.5,76,19.547124
5695,A Feast for Crows,George R. R. Martin,3.5,174,18.076751
5311,Deception Point,Dan Brown,3.5,173,18.056694
5352,Outliers,Malcolm Gladwell,4.0,83,17.723267
5684,Towers of Midnight,"Robert Jordan, Brandon Sanderson",4.5,41,16.819513

In [37]:
#Create Popular Recommendation Function
def recommend_popular(n=10):
    
    top_books = df.sort_values(by='popularity_score', ascending=False).head(n)
    
    for _, book in top_books.iterrows():
        print(book['title'], "-", book['authors'], "(Rating:", book['average_rating'], ")")

In [38]:
recommend_popular()

A Game of Thrones - George R. R. Martin (Rating: 4.0 )
Harry Potter and the Deathly Hallows - J.K. Rowling (Rating: 4.5 )
A Clash of Kings - George R. R. Martin (Rating: 4.0 )
American Sniper - Chris Kyle, Scott McEwen, Jim DeFelice (Rating: 4.0 )
The Casual Vacancy - J. K. Rowling (Rating: 3.0 )
Harry Potter and the Half-Blood Prince - J.K. Rowling (Rating: 4.5 )
A Feast for Crows - George R. R. Martin (Rating: 3.5 )
Deception Point - Dan Brown (Rating: 3.5 )
Outliers - Malcolm Gladwell (Rating: 4.0 )
Towers of Midnight - Robert Jordan, Brandon Sanderson (Rating: 4.5 )

### HYBRID RECOMMENDATION SYSTEM : Similar Books + Most Popular among similar books

In [39]:
def recommend_hybrid(book_title, n=5):

    book_title = book_title.lower()

    matches = df[df['title'].str.contains(book_title, case=False, na=False)]

    if matches.empty:
        print("Book not found in dataset.")
        return

    index = matches.index[0]

    similarity_scores = list(enumerate(similarity_matrix[index]))

    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    similar_books_index = [i[0] for i in similarity_scores[1:50]]

    similar_books = df.iloc[similar_books_index]

    ranked_books = similar_books.sort_values(by='popularity_score', ascending=False)

    for _, book in ranked_books.head(n).iterrows():
        print(book['title'], "-", book['authors'], "(Rating:", book['average_rating'], ")")

In [40]:
recommend_hybrid("game of thrones")

Small Gods - Terry Pratchett (Rating: 4.5 )
Reaper Man - Terry Pratchett (Rating: 4.0 )
Monstrous Regiment - Terry Pratchett (Rating: 4.0 )
Dodger - Terry Pratchett (Rating: 3.5 )
Sourcery - Terry Pratchett (Rating: 3.5 )